name: "mfu-triage local"
values:
  - key: "baseUrl"
    value: "http://localhost:8000"
  - key: "email"
    value: "opd.nurse@mfu.local"
  - key: "password"
    value: "nurse1234"
  - key: "token"
    value: ""
  - key: "session_id"
    value: ""
  - key: "assessment_id"
    value: ""
  - key: "doctor_id"
    value: ""
  - key: "question_id"
    value: ""
  - key: "schedule_id"
    value: ""
  - key: "user_id"
    value: ""
  - key: "version_id"
    value: ""
  - key: "visit_id"
    value: ""
